// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestfulAPI.Models;

namespace RestfulAPI.Migrations
{
    [DbContext(typeof(TimeCardContext))]
    partial class TimeCardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestfulAPI.Models.TimeCardInfo", b =>
                {
                    b.Property<int>("TiemCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Count")
                        .HasColumnType("float");

                    b.Property<double>("FriInfo")
                        .HasColumnType("float");

                    b.Property<double>("MonInfo")
                        .HasColumnType("float");

                    b.Property<double>("SatInfo")
                        .HasColumnType("float");

                    b.Property<double>("SunInfo")
                        .HasColumnType("float");

                    b.Property<double>("ThuInfo")
                        .HasColumnType("float");

                    b.Property<int>("TimeEntryId")
                        .HasColumnType("int");

                    b.Property<double>("TueInfo")
                        .HasColumnType("float");

                    b.Property<double>("WedInfo")
                        .HasColumnType("float");

                    b.HasKey("TiemCardId");

                    b.HasIndex("TimeEntryId");

                    b.ToTable("TimeCards");
                });

            modelBuilder.Entity("RestfulAPI.Models.TimeEntryInfo", b =>
                {
                    b.Property<int>("TimeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TotalHours")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TimeEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeEntrys");
                });

            modelBuilder.Entity("RestfulAPI.Models.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RestfulAPI.Models.TimeCardInfo", b =>
                {
                    b.HasOne("RestfulAPI.Models.TimeEntryInfo", "TimeEntry")
                        .WithMany("TimeCards")
                        .HasForeignKey("TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeEntry");
                });

            modelBuilder.Entity("RestfulAPI.Models.TimeEntryInfo", b =>
                {
                    b.HasOne("RestfulAPI.Models.UserInfo", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestfulAPI.Models.TimeEntryInfo", b =>
                {
                    b.Navigation("TimeCards");
                });

            modelBuilder.Entity("RestfulAPI.Models.UserInfo", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
